### ISSUE TITLE
Error: Unexpected annotation data: annotationKey must be defined

### ISSUE THREAD

**Issue by lossfunc** [aidenlx/obsidian-zotero#237]
zotero 导出 obsidian 后，有时候在 obsidian 那边删了，重新在 zotero 那边新建Note，就会失败，console 信息：plugin:zotlit:333 Uncaught (in promise) Error: Unexpected annotation data: annotationKey must be defined

**Comment by DennisFriedl** [comment]
Same problem here.

**Comment by DennisFriedl** [comment]
I'm getting this error with many of my Zotero items now. Here are the logs in the console:
```
[2024-02-12T11:56:55.917] [ERROR] obsidian-zotero:main - Unexpected annotation data {
  attachmentURI: 'http://zotero.org/users/3906100/items/RM9ABLY8',
  pageLabel: '91',
  position: { pageIndex: 14, rects: [ [Array] ] },
  citationItem: {
    uris: [ 'http://zotero.org/users/3906100/items/I5G83YI6' ],
    locator: '91'
  }
} nh(1) [
  co {
    code: 'missing',
    path: We(1) [ 'annotationKey' ],
    data: undefined,
    source: undefined,
    writers: {
      mustBe: [Function: mustBe],
      writeReason: [Function: writeReason],
      addContext: [Function: cI]
    },
    parts: undefined
  },
  byPath: {
    annotationKey: co {
      code: 'missing',
      path: [We],
      data: undefined,
      source: undefined,
      writers: [Object],
      parts: undefined
    }
  },
  count: 1
]
```
and

```
plugin:zotlit:363 Uncaught (in promise) Error: Unexpected annotation data: annotationKey must be defined
    at yM (plugin:zotlit:363:388)
    at Object.replacement (plugin:zotlit:359:39872)
    at k.D (turndown.js:2:9551)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
```

**Comment by DennisFriedl** [comment]
I know when the error occurs now: 
1. Create a note as attachment to a Zotero item
2. Quote parts of the document in this note which are linked to the pages of the document
3. Try to create a literature note for that item -> Error 

Workaround: Go to the quotes in the note -> rightclick -> Unlink. When you unlinked all quotes you can create a literature note.

**Comment by Littledogdudu** [comment]
Hello👋, I find this plugin recently, it's very amazing simple and I like it very much!  
But the operation of dragging and dropping fragments from the paper to the notes in zotero will cause the plugin to be unable to use '[@' cite the paper, let alone generate the corresponding markdown file for the paper. As following:

![Image](https://github.com/user-attachments/assets/b1ab79bf-b03a-4cd0-bc07-11c5820fca8b)

the error log as following:

```log
[2025-09-29T16:57:44.167] [ERROR] obsidian-zotero:main - Unexpected annotation data {
  attachmentURI: 'http://zotero.org/users/14756662/items/WG28IS26',
  pageLabel: '1',
  position: { pageIndex: 0, rects: [ [Array], [Array], [Array] ] },
  citationItem: {
    uris: [ 'http://zotero.org/users/14756662/items/DF7FF7P3' ],
    locator: '1'
  }
} bb(1) [
  bi {
    code: 'missing',
    path: Je(1) [ 'annotationKey' ],
    data: undefined,
    source: undefined,
    writers: {
      mustBe: [Function: mustBe],
      writeReason: [Function: writeReason],
      addContext: [Function: LC]
    },
    parts: undefined
  },
  byPath: {
    annotationKey: bi {
      code: 'missing',
      path: [Je],
      data: undefined,
      source: undefined,
      writers: [Object],
      parts: undefined
    }
  },
  count: 1
]
plugin:zotlit:365 Uncaught (in promise) Error: Unexpected annotation data: annotationKey must be defined
    at Gq (plugin:zotlit:365:389)
    at Object.replacement (plugin:zotlit:361:39924)
    at k.D (turndown.js:2:9605)
    at turndown.js:2:9264
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9113)
    at k.D (turndown.js:2:9513)
    at turndown.js:2:9264
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9113)
```

Environment:
zotlit=1.1.11
zotero=7.0.24

thanks

**Comment by aidenlx** [comment]
Hey! ZotLit v2 handles this gracefully now. If an annotation's data is missing or malformed, the import skips that annotation and keeps the rest of the note intact instead of crashing.

v2 beta is available now: https://zotlit.aidenlx.site/docs/install-zotlit
Migration guide: https://zotlit.aidenlx.site/docs/how-to/migrate-from-v1
